export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER'
export const GET_FORECAST = 'GET_FORECAST'

export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER'
export const SET_FORECAST = 'SET_FORECAST'
